server:
  port: 9000

# \u670D\u52A1\u540D\u79F0
spring:
  application:
    name: api-gateaway

# \u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# \u81EA\u5B9A\u4E49\u8DEF\u7531\u6620\u5C04
zuul:
  routes:
    order-service: /apigateaway/order/**
    product-service: /apigateaway/product/**
  ignored-patterns: /*-service/**   #\u6B63\u5219\u5339\u914D\u76F8\u5173\u7684\u8DEF\u5F84
  sensitiveHeaders:                #\u5904\u7406\u83B7\u53D6\u4E0D\u5230cookie\u7684\u95EE\u9898\uFF0C\u7F6E\u4E3A\u7A7A
  #  ignored-services: order-service #\u5FFD\u7565\u8DEF\u7531,\u65E0\u6CD5\u901A\u8FC7\u8BE5\u8DEF\u7531\u8BBF\u95EE